---
- hosts: all
  become: yes
  become_method: sudo
  remote_user: vagrant
  connection: ssh
  gather_facts: no

  vars:
    website_dir: /var/www/oursite.dev/web

  tasks:
  - name: Install Apache
    apt: 
      pkg: apache2
      state: latest
    notify:
      start_apache
  
  - name: Create website directory
    file: 
      path: "{{ website_dir }}"
      state: directory
      mode: 775
      owner: www-data
      group: www-data

  handlers:
  - name: start_apache
    service:
      name: apache2
      state: started
  - name: restart_apache
    service:
      name: apache2
      state: restarted
